In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:\\Users\\ACER\\Documents\\Marvel Cinematic Universe Intelligence Dashboard & Success Prediction System\\mcu_final_cleaned_dataset.csv")

In [4]:
df.head()

,title,release_year,mcu_phase_number,imdb-rating,rt_tomato_meter,rt_audience_score,production_budget,domestic_box_office,international_box_office,worldwide_box_office,...,trailer_likes,trailer_count,runtime (mins),genres,num votes,opening weekend,director,profit,roi,decade
0,iron man,2008,1,7.9,94,91,140000000.0,319034126.0,266762121.0,585796247.0,...,7600,2,126,"Action, Adventure, Sci-Fi",1226243,102118668.0,Jon Favreau,445796247.0,318.425891,2000
1,the incredible hulk,2008,1,6.6,67,70,140000000.0,134806913.0,128620638.0,263427551.0,...,31000,2,112,"Action, Sci-Fi",565286,55414050.0,Louis Leterrier,123427551.0,88.162536,2000
2,iron man 2,2010,1,6.9,72,71,200000000.0,312433331.0,311500000.0,623933331.0,...,18000,2,124,"Action, Sci-Fi",939136,128122480.0,Jon Favreau,423933331.0,211.966666,2010
3,thor,2011,1,7.0,77,76,150000000.0,181030624.0,268295994.0,449326618.0,...,85000,2,115,"Action, Fantasy",966962,65723338.0,Kenneth Brangh,299326618.0,199.551079,2010
4,captain america the first avenger,2011,1,6.9,79,75,140000000.0,176654505.0,193915269.0,370569774.0,...,116000,2,124,"Action, Adventure, Sci-Fi",968488,65058524.0,Joe Johnston,230569774.0,164.692696,2010

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     49 non-null     str
 1   release_year              49 non-null     int64
 2   mcu_phase_number          49 non-null     int64
 3   imdb-rating               49 non-null     float64
 4   rt_tomato_meter           49 non-null     int64
 5   rt_audience_score         49 non-null     int64
 6   production_budget         49 non-null     float64
 7   domestic_box_office       36 non-null     float64
 8   international_box_office  36 non-null     float64
 9   worldwide_box_office      36 non-null     float64
 10  trailer_views             49 non-null     int64
 11  trailer_likes             49 non-null     int64
 12  trailer_count             49 non-null     int64
 13  runtime (mins)            49 non-null     int64
 14  genres                    49 non-null     str
 15  num votes                 49 non-null     int64
 16  opening weekend           35 non-null     float64
 17  director                  49 non-null     str
 18  profit                    36 non-null     float64
 19  roi                       36 non-null     float64
 20  decade                    49 non-null     int64
dtypes: float64(8), int64(10), str(3)
memory usage: 8.2 KB

In [6]:
df.describe()

,release_year,mcu_phase_number,imdb-rating,rt_tomato_meter,rt_audience_score,production_budget,domestic_box_office,international_box_office,worldwide_box_office,trailer_views,trailer_likes,trailer_count,runtime (mins),num votes,opening weekend,profit,roi,decade
count,49.000000,49.000000,49.000000,49.000000,49.000000,4.900000e+01,3.600000e+01,3.600000e+01,3.600000e+01,4.900000e+01,4.900000e+01,49.000000,49.000000,4.900000e+01,3.500000e+01,3.600000e+01,36.000000,49.000000
mean,2018.857143,3.387755,7.075510,81.387755,81.877551,1.868694e+08,3.563028e+08,5.315331e+08,8.878235e+08,5.857959e+07,9.166041e+05,2.102041,108.061224,6.122796e+05,1.305300e+08,6.856568e+08,334.121513,2014.897959
std,4.721405,1.304101,0.847676,13.092327,13.517940,6.184337e+07,1.938443e+08,3.740889e+08,5.513392e+08,6.478841e+07,9.263995e+05,0.510102,40.377081,4.099007e+05,7.005317e+07,5.251316e+08,205.063910,5.817520
min,2008.000000,1.000000,4.500000,46.000000,32.000000,1.960000e+07,8.450022e+07,1.216127e+08,2.061129e+08,1.500000e+06,7.600000e+03,1.000000,30.000000,8.000000e+03,4.611086e+07,-6.388707e+07,-23.661877,2000.000000
25%,2016.000000,3.000000,6.700000,77.000000,78.000000,1.500000e+08,2.048966e+08,2.654632e+08,4.693850e+08,2.600000e+07,2.900000e+05,2.000000,60.000000,2.703550e+05,7.808926e+07,2.950558e+08,196.703858,2010.000000
50%,2021.000000,4.000000,7.200000,85.000000,86.000000,1.800000e+08,3.261054e+08,4.423789e+08,7.669012e+08,3.800000e+07,7.600000e+05,2.000000,123.000000,5.440000e+05,1.061096e+08,5.699886e+08,314.582156,2020.000000
75%,2022.000000,4.000000,7.700000,92.000000,91.000000,2.200000e+08,4.152062e+08,7.014000e+08,1.137143e+09,6.200000e+07,1.200000e+06,2.000000,134.000000,9.287100e+05,1.766419e+08,9.729215e+08,472.767560,2020.000000
max,2025.000000,5.000000,8.400000,98.000000,98.000000,3.560000e+08,8.583720e+08,1.939558e+09,2.797801e+09,3.650000e+08,4.200000e+06,4.000000,181.000000,1.559778e+06,3.571150e+08,2.441801e+09,860.923556,2020.000000

In [7]:
df["success_category"] = np.where(
    df["profit"] > 0,
    "Hit",
    "Flop"
)

In [8]:
df.head()

,title,release_year,mcu_phase_number,imdb-rating,rt_tomato_meter,rt_audience_score,production_budget,domestic_box_office,international_box_office,worldwide_box_office,...,trailer_count,runtime (mins),genres,num votes,opening weekend,director,profit,roi,decade,success_category
0,iron man,2008,1,7.9,94,91,140000000.0,319034126.0,266762121.0,585796247.0,...,2,126,"Action, Adventure, Sci-Fi",1226243,102118668.0,Jon Favreau,445796247.0,318.425891,2000,Hit
1,the incredible hulk,2008,1,6.6,67,70,140000000.0,134806913.0,128620638.0,263427551.0,...,2,112,"Action, Sci-Fi",565286,55414050.0,Louis Leterrier,123427551.0,88.162536,2000,Hit
2,iron man 2,2010,1,6.9,72,71,200000000.0,312433331.0,311500000.0,623933331.0,...,2,124,"Action, Sci-Fi",939136,128122480.0,Jon Favreau,423933331.0,211.966666,2010,Hit
3,thor,2011,1,7.0,77,76,150000000.0,181030624.0,268295994.0,449326618.0,...,2,115,"Action, Fantasy",966962,65723338.0,Kenneth Brangh,299326618.0,199.551079,2010,Hit
4,captain america the first avenger,2011,1,6.9,79,75,140000000.0,176654505.0,193915269.0,370569774.0,...,2,124,"Action, Adventure, Sci-Fi",968488,65058524.0,Joe Johnston,230569774.0,164.692696,2010,Hit

In [9]:
df.groupby(
    "mcu_phase_number"
)["worldwide_box_office"].mean()

mcu_phase_number
1    6.353089e+08
2    8.782705e+08
3    1.227737e+09
4    8.159742e+08
5    6.105400e+08
Name: worldwide_box_office, dtype: float64

In [10]:
df.groupby(
    "mcu_phase_number"
)["imdb-rating"].mean()

mcu_phase_number
1    7.216667
2    7.350000
3    7.590909
4    7.026667
5    6.400000
Name: imdb-rating, dtype: float64

In [11]:
df.groupby(
    "director"
)["worldwide_box_office"].sum()

director
Adil El Arbi , Bilall Fallah ,Meera Memon , Sharmeen & Obaid-Chinoy    0.000000e+00
Alan Taylor                                                            6.447831e+08
Ali Selim                                                              0.000000e+00
Anna Boden & Ryan Fleck                                                1.128430e+09
Anthony and Joe Russo                                                  6.713897e+09
Bryan Andrews & Stephan Franck                                         0.000000e+00
Cate Shortland                                                         3.797517e+08
Chloe Zhao                                                             4.020649e+08
Destin Daniel Cretton                                                  4.322433e+08
Jake Schreier                                                          3.824000e+08
James Gunn                                                             2.482186e+09
Joe Johnston                                                           3.705698e+08
Jon Favreau                                                            1.209730e+09
Jon Watts                                                              3.933972e+09
Joss Whedon                                                            2.921592e+09
Julius Onah                                                            4.151000e+08
Justin Benson & Aaron Moorhead                                         0.000000e+00
Kari Skogland                                                          0.000000e+00
Kat Coiro &Anu Valia                                                   0.000000e+00
Kate Herron , Justin Benson  & Aaron Moorhead                          0.000000e+00
Kenneth Brangh                                                         4.493266e+08
Louis Leterrier                                                        2.634276e+08
Matt Shakman                                                           0.000000e+00
Mohamed Diab , Justin Benson & Aaron Moorhead                          0.000000e+00
Nia DaCosta                                                            2.061129e+08
Peyton Reed                                                            1.618057e+09
Rhys Thomas, Bert & Bertie                                             0.000000e+00
Ryan Coogler                                                           2.206122e+09
Sam Bailey & Angela Barnes                                             0.000000e+00
Sam Raimi                                                              9.557758e+08
Scott Derrickson                                                       6.777184e+08
Shane Black                                                            1.215440e+09
Shawn Levy                                                             1.338000e+09
Sydney Freeland & Catriona McKenzie                                    0.000000e+00
Taika Waititi                                                          1.614945e+09
Todd Harris                                                            0.000000e+00
Name: worldwide_box_office, dtype: float64

In [13]:
numeric_df = df.select_dtypes(
    include=np.number
)

numeric_df.corr()

,release_year,mcu_phase_number,imdb-rating,rt_tomato_meter,rt_audience_score,production_budget,domestic_box_office,international_box_office,worldwide_box_office,trailer_views,trailer_likes,trailer_count,runtime (mins),num votes,opening weekend,profit,roi,decade
release_year,1.000000,0.976887,-0.344452,-0.127157,-0.047284,0.030801,0.111338,0.030329,0.059718,0.258891,0.325413,-0.270630,-0.404082,-0.745808,0.122455,0.022360,-0.065377,0.890683
mcu_phase_number,0.976887,1.000000,-0.356842,-0.187139,-0.044522,0.014642,0.029921,-0.058491,-0.029167,0.224184,0.259086,-0.248624,-0.414707,-0.775533,0.049775,-0.067963,-0.154463,0.870332
imdb-rating,-0.344452,-0.356842,1.000000,0.571357,0.686794,0.184279,0.640440,0.654867,0.669501,0.258312,0.306351,0.266075,0.353753,0.646225,0.565712,0.692180,0.687513,-0.359613
rt_tomato_meter,-0.127157,-0.187139,0.571357,1.000000,0.446060,-0.167921,0.457624,0.406441,0.436657,0.020049,0.104809,-0.096513,-0.064363,0.298270,0.339205,0.469400,0.566110,-0.197779
rt_audience_score,-0.047284,-0.044522,0.686794,0.446060,1.000000,0.136808,0.286366,0.218622,0.249041,0.228437,0.223998,0.164999,0.367545,0.312738,0.218788,0.238743,0.166553,-0.026654
production_budget,0.030801,0.014642,0.184279,-0.167921,0.136808,1.000000,0.448508,0.547222,0.528981,0.437676,0.593222,0.313726,0.545973,0.348009,0.602272,0.454031,0.095888,0.006795
domestic_box_office,0.111338,0.029921,0.640440,0.457624,0.286366,0.448508,1.000000,0.872015,0.943250,0.557050,0.621912,-0.029255,0.573170,0.550964,0.954846,0.944868,0.873985,-0.023559
international_box_office,0.030329,-0.058491,0.654867,0.406441,0.218622,0.547222,0.872015,1.000000,0.985076,0.526289,0.651842,0.010002,0.624431,0.617832,0.910650,0.978777,0.823436,-0.152071
worldwide_box_office,0.059718,-0.029167,0.669501,0.436657,0.249041,0.528981,0.943250,0.985076,1.000000,0.552943,0.660928,-0.003484,0.625194,0.612917,0.953389,0.996294,0.865976,-0.111453
trailer_views,0.258891,0.224184,0.258312,0.020049,0.228437,0.437676,0.557050,0.526289,0.552943,1.000000,0.604807,0.010150,0.288995,0.190048,0.568756,0.537943,0.412743,0.080419
trailer_likes,0.325413,0.259086,0.306351,0.104809,0.223998,0.593222,0.621912,0.651842,0.660928,0.604807,1.000000,0.016091,0.281891,0.166900,0.684683,0.624480,0.416382,0.223006
trailer_count,-0.270630,-0.248624,0.266075,-0.096513,0.164999,0.313726,-0.029255,0.010002,-0.003484,0.010150,0.016091,1.000000,0.346636,0.380098,-0.044405,-0.016193,-0.016814,-0.242133
runtime (mins),-0.404082,-0.414707,0.353753,-0.064363,0.367545,0.545973,0.573170,0.624431,0.625194,0.288995,0.281891,0.346636,1.000000,0.675358,0.648337,0.601047,0.394150,-0.472259
num votes,-0.745808,-0.775533,0.646225,0.298270,0.312738,0.348009,0.550964,0.617832,0.612917,0.190048,0.166900,0.380098,0.675358,1.000000,0.526618,0.634292,0.609656,-0.737697
opening weekend,0.122455,0.049775,0.565712,0.339205,0.218788,0.602272,0.954846,0.910650,0.953389,0.568756,0.684683,-0.044405,0.648337,0.526618,1.000000,0.942465,0.788145,-0.003669
profit,0.022360,-0.067963,0.692180,0.469400,0.238743,0.454031,0.944868,0.978777,0.996294,0.537943,0.624480,-0.016193,0.601047,0.634292,0.942465,1.000000,0.899476,-0.154205
roi,-0.065377,-0.154463,0.687513,0.566110,0.166553,0.095888,0.873985,0.823436,0.865976,0.412743,0.416382,-0.016814,0.394150,0.609656,0.788145,0.899476,1.000000,-0.243279
decade,0.890683,0.870332,-0.359613,-0.197779,-0.026654,0.006795,-0.023559,-0.152071,-0.111453,0.080419,0.223006,-0.242133,-0.472259,-0.737697,-0.003669,-0.154205,-0.243279,1.000000

In [ ]:
sns.heatmap(numeric_df.corr())

TypeError: heatmap() missing 1 required positional argument: 'data'