### Import Libraries

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

### Load Data

In [4]:
df = pd.read_csv("C:\\Users\\ACER\\Documents\\Marvel Cinematic Universe Intelligence Dashboard & Success Prediction System\\notebooks\\Marvel_MCU_Final_Analytics_Dataset_Power_BI.csv")
df.head()

,title,type,release_year,mcu_phase_number,imdb_rating,rt_tomato_meter,rt_audience_score,production_budget,domestic_box_office,international_box_office,...,decade,success_category,success_encoded,success_score,imdb_scaled,audience_scaled,roi_scaled,cluster,cluster_name,Marvel_Cluster
0,iron man,Movie,2008,1,7.9,94,91,140000000,319034126,266762121,...,2000,Hit,2,73.291607,0.871795,0.893939,0.386721,2,Struggling Titles,NaN
1,the incredible hulk,Movie,2008,1,6.6,67,70,140000000,134806913,128620638,...,2000,Hit,2,42.603623,0.538462,0.575758,0.126414,1,Successful Heroes,NaN
2,iron man 2,Movie,2010,1,6.9,72,71,200000000,312433331,311500000,...,2010,Hit,2,50.333809,0.615385,0.590909,0.266372,2,Struggling Titles,NaN
3,thor,Movie,2011,1,7.0,77,76,150000000,181030624,268295994,...,2010,Hit,2,53.211113,0.641026,0.666667,0.252336,2,Struggling Titles,NaN
4,captain america the first avenger,Movie,2011,1,6.9,79,75,140000000,176654505,193915269,...,2010,Hit,2,50.548732,0.615385,0.651515,0.212930,2,Struggling Titles,NaN

Column Creation

In [21]:
df["content"] = (

    df["genres"]

    + " "

    + df["director"]

    + " "

    + df["success_category"]
    
    + " "
    
    + df["type"]

    + " Phase"

    + df["mcu_phase_number"].astype(str)
)

### TF-IDF

In [22]:
tfidf = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = tfidf.fit_transform(
    df["content"]
)

### Cosine Similarity

In [23]:
cosine_sim = cosine_similarity(
    tfidf_matrix,
    tfidf_matrix
)

Movie Index

In [24]:
indices = pd.Series(
    df.index,
    index=df["title"]
).drop_duplicates()

### Recommendation Function

In [25]:
def recommend_movies(movie_name):

    idx = indices[movie_name]

    similarity_scores = list(
        enumerate(
            cosine_sim[idx]
        )
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x:x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:6]

    movie_indices = [
        i[0]
        for i in similarity_scores
    ]

    return df[
        ["title"]
    ].iloc[movie_indices]

### Test

In [26]:
recommend_movies("loki")

                     title
32             moon knight
45    daredevil-born again
29                eternals
31  spider-man no way home
23             wandavision

# Marvel Fan Sentiment Analysis

In [27]:
reviews = [

"Spider Man No Way Home is amazing",

"Secret Invasion was disappointing",

"Loki is one of Marvel's best shows",

"The Marvels was boring"

]

In [28]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

for review in reviews:

    score = analyzer.polarity_scores(
        review
    )

    print(
        review,
        score["compound"]
    )

Spider Man No Way Home is amazing 0.3818
Secret Invasion was disappointing -0.4939
Loki is one of Marvel's best shows 0.6369
The Marvels was boring 0.1779